//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace mq.model.dbentity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_BG_LoginLog
    {
        public long ID { get; set; }
        public Nullable<long> LogUserID { get; set; }
        public Nullable<System.DateTime> LogTime { get; set; }
        public string IP { get; set; }
        public string Address { get; set; }
        public Nullable<bool> IsLogIn { get; set; }
        public string Remark { get; set; }
    }
}
