//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace mq.model.dbentity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_BG_UpFiles
    {
        public long Id { get; set; }
        public string filename { get; set; }
        public string filehash { get; set; }
        public Nullable<long> userid { get; set; }
        public string fileoriginname { get; set; }
        public string filepath { get; set; }
        public string ext { get; set; }
        public Nullable<int> filetype { get; set; }
        public string proofreading { get; set; }
        public string proofpath { get; set; }
        public Nullable<System.DateTime> addtime { get; set; }
    }
}
