//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace mq.model.dbentity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_User
    {
        public string Code { get; set; }
        public int Type { get; set; }
        public string Name { get; set; }
        public string DepartmentId { get; set; }
        public string Gender { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string IDCard { get; set; }
        public string StatusCode { get; set; }
        public Nullable<decimal> BasePay { get; set; }
        public Nullable<decimal> OtherAllance { get; set; }
        public string Post { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public Nullable<bool> Frozen { get; set; }
        public Nullable<int> OperationLvl { get; set; }
        public string PassWord { get; set; }
        public bool IsSaler { get; set; }
    }
}
