//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace mq.model.dbentity
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_BG_ActiveFile_Department
    {
        public long Id { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<long> DeparementId { get; set; }
        public string DepartmentName { get; set; }
        public Nullable<System.DateTime> PublicTime { get; set; }
        public Nullable<int> NatureType { get; set; }
        public string FileNewName { get; set; }
        public string FileOriginName { get; set; }
        public string FilePath { get; set; }
        public string FileType { get; set; }
        public string Remark { get; set; }
        public Nullable<int> Lvl { get; set; }
        public Nullable<int> IsDel { get; set; }
    }
}
